import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { prisma } from "@/lib/prisma";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  header: { marginBottom: 30 },
  houseName: { fontSize: 18, fontWeight: "bold", marginBottom: 4 },
  houseAddress: { fontSize: 10, color: "#555" },
  houseContact: { fontSize: 9, color: "#777", marginTop: 2 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#ddd", marginVertical: 15 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  label: { fontSize: 9, color: "#777", textTransform: "uppercase" as const },
  value: { fontSize: 11 },
  amountSection: { marginTop: 20, padding: 15, backgroundColor: "#f7f9fc", borderRadius: 4 },
  amountLabel: { fontSize: 10, color: "#555" },
  amountValue: { fontSize: 22, fontWeight: "bold", marginTop: 4 },
  footer: { position: "absolute" as const, bottom: 30, left: 40, right: 40, fontSize: 8, color: "#999", textAlign: "center" as const },
  statusBadge: { fontSize: 10, fontWeight: "bold", padding: "3 8", borderRadius: 4 },
});

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(amount);
}

function formatDate(date: Date): string {
  return new Intl.DateTimeFormat("en-PH", { year: "numeric", month: "long", day: "numeric" }).format(date);
}

type InvoiceData = {
  invoiceNumber: string;
  amount: number;
  dueDate: Date;
  paidDate: Date | null;
  status: string;
  type: string;
  description: string | null;
  createdAt: Date;
  tenant: { name: string; room: { number: string } | null };
  boardingHouse: { name: string; address: string; contactPhone: string | null; contactEmail: string | null };
};

function InvoiceDocument({ invoice }: { invoice: InvoiceData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.houseName}>{invoice.boardingHouse.name}</Text>
          <Text style={styles.houseAddress}>{invoice.boardingHouse.address}</Text>
          {invoice.boardingHouse.contactPhone && (
            <Text style={styles.houseContact}>Tel: {invoice.boardingHouse.contactPhone}</Text>
          )}
          {invoice.boardingHouse.contactEmail && (
            <Text style={styles.houseContact}>Email: {invoice.boardingHouse.contactEmail}</Text>
          )}
        </View>

        <View style={styles.divider} />

        <View style={styles.row}>
          <View>
            <Text style={styles.label}>Invoice Number</Text>
            <Text style={styles.value}>{invoice.invoiceNumber}</Text>
          </View>
          <View>
            <Text style={styles.label}>Status</Text>
            <Text style={styles.statusBadge}>{invoice.status}</Text>
          </View>
        </View>

        <View style={styles.row}>
          <View>
            <Text style={styles.label}>Date Issued</Text>
            <Text style={styles.value}>{formatDate(invoice.createdAt)}</Text>
          </View>
          <View>
            <Text style={styles.label}>Due Date</Text>
            <Text style={styles.value}>{formatDate(invoice.dueDate)}</Text>
          </View>
        </View>

        {invoice.paidDate && (
          <View style={styles.row}>
            <View>
              <Text style={styles.label}>Paid Date</Text>
              <Text style={styles.value}>{formatDate(invoice.paidDate)}</Text>
            </View>
          </View>
        )}

        <View style={styles.divider} />

        <View style={styles.row}>
          <View>
            <Text style={styles.label}>Tenant</Text>
            <Text style={styles.value}>{invoice.tenant.name}</Text>
          </View>
          <View>
            <Text style={styles.label}>Room</Text>
            <Text style={styles.value}>{invoice.tenant.room ? `Room ${invoice.tenant.room.number}` : "N/A"}</Text>
          </View>
        </View>

        <View style={styles.divider} />

        <View style={styles.row}>
          <View>
            <Text style={styles.label}>Type</Text>
            <Text style={styles.value}>{invoice.type}</Text>
          </View>
          <View>
            <Text style={styles.label}>Description</Text>
            <Text style={styles.value}>{invoice.description || "-"}</Text>
          </View>
        </View>

        <View style={styles.amountSection}>
          <Text style={styles.amountLabel}>Total Amount</Text>
          <Text style={styles.amountValue}>{formatCurrency(invoice.amount)}</Text>
        </View>

        <Text style={styles.footer}>
          Generated by Phase on {formatDate(new Date())}
        </Text>
      </Page>
    </Document>
  );
}

export async function generateInvoicePDF(invoiceId: string): Promise<Buffer> {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      tenant: { select: { name: true, room: { select: { number: true } } } },
      boardingHouse: { select: { name: true, address: true, contactPhone: true, contactEmail: true } },
    },
  });

  if (!invoice) throw new Error("Invoice not found");

  const buffer = await renderToBuffer(<InvoiceDocument invoice={invoice} />);
  return Buffer.from(buffer);
}
